--- #YAML:1.0
name:                VS-Chart
version:             0.01
abstract:            Simple module to create beautifully looking charts
license:             mit
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Cairo:                         0
    Date::Simple:                  0
    List::MoreUtils:               0
    List::Util:                    0
    Scalar::Util:                  0
    Test::Exception:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Claes Jakobsson <claes@versed.se>
